import type { ThemeDefinition } from 'vuetify'

export const staticPrimaryColor = '#6366F1'
export const staticPrimaryDarkenColor = '#4F46E5'

export const themes: Record<string, ThemeDefinition> = {
  light: {
    dark: false,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#fff',
      'primary-darken-1': staticPrimaryDarkenColor,
      'secondary': '#64748B',
      'on-secondary': '#fff',
      'secondary-darken-1': '#475569',
      'success': '#10B981',
      'on-success': '#fff',
      'success-darken-1': '#059669',
      'info': '#0EA5E9',
      'on-info': '#fff',
      'info-darken-1': '#0284C7',
      'warning': '#F59E0B',
      'on-warning': '#fff',
      'warning-darken-1': '#D97706',
      'error': '#EF4444',
      'on-error': '#fff',
      'error-darken-1': '#DC2626',
      'background': '#F8FAFC',
      'on-background': '#0F172A',
      'surface': '#FFFFFF',
      'on-surface': '#0F172A',
      'grey-50': '#F8FAFC',
      'grey-100': '#F1F5F9',
      'grey-200': '#E2E8F0',
      'grey-300': '#CBD5E1',
      'grey-400': '#94A3B8',
      'grey-500': '#64748B',
      'grey-600': '#475569',
      'grey-700': '#334155',
      'grey-800': '#1E293B',
      'grey-900': '#0F172A',
      'grey-light': '#F8FAFC',
      'perfect-scrollbar-thumb': '#CBD5E1',
      'skin-bordered-background': '#fff',
      'skin-bordered-surface': '#fff',
      'expansion-panel-text-custom-bg': '#f8fafc',
    },

    variables: {
      'code-color': '#6366F1',
      'overlay-scrim-background': '#0F172A',
      'tooltip-background': '#0F172A',
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.04,
      'focus-opacity': 0.08,
      'selected-opacity': 0.08,
      'activated-opacity': 0.12,
      'pressed-opacity': 0.12,
      'dragged-opacity': 0.08,
      'disabled-opacity': 0.38,
      'border-color': '#0F172A',
      'border-opacity': 0.08,
      'table-header-color': '#F1F5F9',
      'high-emphasis-opacity': 0.87,
      'medium-emphasis-opacity': 0.6,
      'switch-opacity': 0.2,
      'switch-disabled-track-opacity': 0.3,
      'switch-disabled-thumb-opacity': 0.4,
      'switch-checked-disabled-opacity': 0.3,
      'track-bg': '#E2E8F0',

      'shadow-key-umbra-color': '#0F172A',
      'shadow-xs-opacity': 0.05,
      'shadow-sm-opacity': 0.06,
      'shadow-md-opacity': 0.08,
      'shadow-lg-opacity': 0.10,
      'shadow-xl-opacity': 0.15,
    },
  },
  dark: {
    dark: true,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#fff',
      'primary-darken-1': '#675DD8',
      'secondary': '#94A3B8',
      'on-secondary': '#fff',
      'secondary-darken-1': '#737682',
      'success': '#10B981',
      'on-success': '#fff',
      'success-darken-1': '#24B364',
      'info': '#38BDF8',
      'on-info': '#fff',
      'info-darken-1': '#00A7BC',
      'warning': '#FBBF24',
      'on-warning': '#fff',
      'warning-darken-1': '#E68F3C',
      'error': '#F87171',
      'on-error': '#fff',
      'error-darken-1': '#E64449',
      'background': '#071314',
      'on-background': '#E6FFFB',
      'surface': '#0E1E20',
      'on-surface': '#E6FFFB',
      'grey-50': '#102326',
      'grey-100': '#12292C',
      'grey-200': '#163438',
      'grey-300': '#285056',
      'grey-400': '#40727B',
      'grey-500': '#63A4AE',
      'grey-600': '#8AC4CB',
      'grey-700': '#B5E2E6',
      'grey-800': '#D3F1F2',
      'grey-900': '#ECFBFB',
      'grey-light': '#153337',
      'perfect-scrollbar-thumb': '#285056',
      'skin-bordered-background': '#0E1E20',
      'skin-bordered-surface': '#0E1E20',
    },
    variables: {
      'code-color': '#5EEAD4',
      'overlay-scrim-background': '#031011',
      'tooltip-background': '#E6FFFB',
      'overlay-scrim-opacity': 0.6,
      'hover-opacity': 0.06,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': '#D3F1F2',
      'border-opacity': 0.10,
      'table-header-color': '#173A3E',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,
      'switch-opacity': 0.4,
      'switch-disabled-track-opacity': 0.4,
      'switch-disabled-thumb-opacity': 0.8,
      'switch-checked-disabled-opacity': 0.3,
      'track-bg': '#173A3E',

      'shadow-key-umbra-color': '#020617',
      'shadow-xs-opacity': 0.16,
      'shadow-sm-opacity': 0.18,
      'shadow-md-opacity': 0.22,
      'shadow-lg-opacity': 0.26,
      'shadow-xl-opacity': 0.30,
    },
  },
}

export default themes
