/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin-dashboard': RouteRecordInfo<'admin-dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    'admin-settings': RouteRecordInfo<'admin-settings', '/admin/settings', Record<never, never>, Record<never, never>>,
    'admin-status': RouteRecordInfo<'admin-status', '/admin/status', Record<never, never>, Record<never, never>>,
    'admin-users': RouteRecordInfo<'admin-users', '/admin/users', Record<never, never>, Record<never, never>>,
    'admin-validations': RouteRecordInfo<'admin-validations', '/admin/validations', Record<never, never>, Record<never, never>>,
    'admin-withdrawals': RouteRecordInfo<'admin-withdrawals', '/admin/withdrawals', Record<never, never>, Record<never, never>>,
    'checkout-order-id': RouteRecordInfo<'checkout-order-id', '/checkout/:orderId', { orderId: ParamValue<true> }, { orderId: ParamValue<false> }>,
    'dashboard-tickets': RouteRecordInfo<'dashboard-tickets', '/dashboard/tickets', Record<never, never>, Record<never, never>>,
    'events': RouteRecordInfo<'events', '/events', Record<never, never>, Record<never, never>>,
    'events-slug': RouteRecordInfo<'events-slug', '/events/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    'events-create': RouteRecordInfo<'events-create', '/events/create', Record<never, never>, Record<never, never>>,
    'faq': RouteRecordInfo<'faq', '/faq', Record<never, never>, Record<never, never>>,
    'history': RouteRecordInfo<'history', '/history', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'organizer-dashboard': RouteRecordInfo<'organizer-dashboard', '/organizer/dashboard', Record<never, never>, Record<never, never>>,
    'pricing': RouteRecordInfo<'pricing', '/pricing', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'settings': RouteRecordInfo<'settings', '/settings', Record<never, never>, Record<never, never>>,
    'status': RouteRecordInfo<'status', '/status', Record<never, never>, Record<never, never>>,
    'support': RouteRecordInfo<'support', '/support', Record<never, never>, Record<never, never>>,
    'tickets-verify': RouteRecordInfo<'tickets-verify', '/tickets/verify', Record<never, never>, Record<never, never>>,
    'wallet': RouteRecordInfo<'wallet', '/wallet', Record<never, never>, Record<never, never>>,
  }
}
