# Generated by Django 6.0.4 on 2026-04-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_status_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
