# Generated by Django 4.2.30 on 2026-04-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_fix_seeded_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='approval_note',
        ),
        migrations.RemoveField(
            model_name='user',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='status_note',
            field=models.TextField(blank=True),
        ),
    ]
